const LEVELS = {
  bronze: {
    id: 1,
    name: 'Bronze',
    startScore: 0,
    endScore: 10000,
    energy: 3,
    nitro: 5,
    farming: 3,
    gamebot: null,
    fractal: null,
    rechargeSpeed: null,
  },
  silver: {
    id: 2,
    name: 'Silver',
    startScore: 10000,
    endScore: 100000,
    energy: 4,
    nitro: 5,
    rechargeSpeed: null,
    farming: 6,
    gamebot: 4,
    fractal: null,
  },
  gold: {
    id: 3,
    name: 'Gold',
    startScore: 100001,
    endScore: 250000,
    energy: 5,
    nitro: 8,
    rechargeSpeed: 6,
    farming: 6,
    gamebot: 4,
    fractal: 100,
  },
  platinum: {
    id: 4,
    name: 'Platinum',
    startScore: 250001,
    endScore: 500000,
    energy: 3,
    nitro: 5,
    rechargeSpeed: 6,
    farming: 12,
    gamebot: 4,
    fractal: 100,
  },
}

export { LEVELS }
